### ISSUE TITLE
problem while using python3

### ISSUE THREAD

**Issue by revanth7667** [robintibor/python-mindwave-mobile#21]
hi ,
i'm trying to connect the Mindwave Mobile 2 with my laptop running ubuntu 18.04 and use with python3 however i get an error message

```
Discovered Mindwave Mobile...
Traceback (most recent call last):
  File "read_mindwave_mobile.py", line 12, in <module>
    dataPoint = mindwaveDataPointReader.readNextDataPoint()
  File "/home/revanth/python-mindwave-mobile/mindwavemobile/MindwaveDataPointReader.py", line 20, in readNextDataPoint
    self._putNextDataPointsInQueue()
  File "/home/revanth/python-mindwave-mobile/mindwavemobile/MindwaveDataPointReader.py", line 30, in _putNextDataPointsInQueue
    dataPoints = self._readDataPointsFromOnePacket()
  File "/home/revanth/python-mindwave-mobile/mindwavemobile/MindwaveDataPointReader.py", line 34, in _readDataPointsFromOnePacket
    self._goToStartOfNextPacket()
  File "/home/revanth/python-mindwave-mobile/mindwavemobile/MindwaveDataPointReader.py", line 46, in _goToStartOfNextPacket
    byte = self._mindwaveMobileRawReader.getByte()
  File "/home/revanth/python-mindwave-mobile/mindwavemobile/MindwaveMobileRawReader.py", line 74, in getByte
    self._ensureMoreBytesCanBeRead(100);
  File "/home/revanth/python-mindwave-mobile/mindwavemobile/MindwaveMobileRawReader.py", line 79, in _ensureMoreBytesCanBeRead
    self._readMoreBytesIntoBuffer(amountOfBytes)
  File "/home/revanth/python-mindwave-mobile/mindwavemobile/MindwaveMobileRawReader.py", line 56, in _readMoreBytesIntoBuffer
    newBytes = self._readBytesFromMindwaveMobile(amountOfBytes)
  File "/home/revanth/python-mindwave-mobile/mindwavemobile/MindwaveMobileRawReader.py", line 65, in _readBytesFromMindwaveMobile
    receivedBytes += self.mindwaveMobileSocket.recv(missingBytes)
TypeError: must be str, not bytes

```
however i get no such error message when i execute with python2.
 new to python so sorry if silly problem

**Comment by KudosAbhay** [comment]
I'm getting the same error as well. Someone please help

**Comment by BioMycoBit** [comment]
In python 3, bytes and str instances cannot be used together with operators (like > or +).  With a byte string you can decode via .decode() but utf-8 does not work

**Comment by BioMycoBit** [comment]
These updates got my code working for python 3.

MindwaveMobileRawReader.py

    def _readBytesFromMindwaveMobile(self, amountOfBytes):
        # receivedBytes = ""
        receivedBytes = b''

    def _getNextByte(self):
        # nextByte = ord(self._buffer[self._bufferPosition])
        nextByte = self._buffer[self._bufferPosition]
    
    def _getNextBytes(self, amountOfBytes):
        # nextBytes = list(map(ord, self._buffer[self._bufferPosition: self._bufferPosition + amountOfBytes]))
        nextBytes = list(self._buffer[self._bufferPosition: self._bufferPosition + amountOfBytes])

**Comment by robintibor** [comment]
@BioMycoBit seems great, would you be willing to make a pull request out of it?

**Comment by revanth7667** [comment]
Thanks!
I have tried it and it works, I have tested only the sample code. I will try other cases as well a let you know if any issues are present

**Comment by BioMycoBit** [comment]
> @BioMycoBit seems great, would you be willing to make a pull request out of it?

@robintibor see pull request.  https://github.com/robintibor/python-mindwave-mobile/pulls

**Comment by robintibor** [comment]
Amazing thanks @BioMycoBit
